name: CI/CD

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Run tests and capture log
        run: |
          npm test -- --watch=false --browsers=ChromeHeadless > test.log
      - name: Agentic Auto-Fix (LangChain)
        if: failure()
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          pip install langchain langchain_community langchain-google-genai
          python auto_fix_agent.py test.log
      - name: Read diff file
        if: failure()
        id: read_diff
        run: |
          echo "diff_content<<EOF" >> $GITHUB_OUTPUT
          cat src/app/dashboard/dashboard.component.spec.diff >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Post agentic diff as PR comment
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            💡 **Agentic Auto-Fix Suggestion (Diff) for `src/app/dashboard/dashboard.component.spec.ts`:**

            ```diff
            ${{ steps.read_diff.outputs.diff_content }}
            ```
      - name: Build
        run: npm run build 