name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Run tests and capture log
        run: |
          npm test -- --watch=false --browsers=ChromeHeadless > test.log
      - name: Agentic Auto-Fix (LangChain)
        if: failure()
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          pip install langchain langchain_community langchain-google-genai
          python auto_fix_agent.py test.log
      - name: Create Pull Request with Fix
        uses: peter-evans/create-pull-request@v6
        if: success()
        with:
          commit-message: "fix(agentic): Apply automated fix for failing tests"
          title: "🤖 Agentic Fix for Failing Tests"
          body: |
            The agentic CI/CD layer detected a test failure and has automatically generated a fix.
            Please review the changes and merge if they are correct.
          branch: "agentic-fix"
          delete-branch: true
      - name: Build
        run: npm run build 